definitions:
  dtos.ErrorResponse:
    properties:
      error:
        example: Specific error message
        type: string
    type: object
  models.Organization:
    properties:
      address:
        example: 295 Varnum Ave
        type: string
      id:
        example: 86e6a1f3-d7aa-4e74-a20a-ea78bc13340b
        type: string
      name:
        example: The Lowell General Hospital
        type: string
    type: object
host: localhost:4000
info:
  contact: {}
  title: Igaku Encounter API
  version: 0.0.1
paths:
  /encounter/health:
    get:
      description: Returns an OK message
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check health
      tags:
      - Health
  /encounter/organizations/{id}:
    get:
      description: Retrieves details for a specific organization using its UUID.
      parameters:
      - description: Organization ID (UUIDv4 format)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved organization
          schema:
            $ref: '#/definitions/models.Organization'
        "400":
          description: Bad Request - Invalid UUID format
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "404":
          description: Not Found - Organization not found
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: Internal Server Error - Failed to retrieve organization
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Get organization by ID
      tags:
      - Organizations
swagger: "2.0"
