root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -C auth-service -buildvcs=false -o tmp/main igaku/auth-service"
bin = "auth-service/tmp/main"
include_ext = ["go"]
exclude_dir = ["auth-service/tmp", "auth-service/bin"]
log = "air_auth.log"
delay = 1000
stop_on_error = true

[misc]
clean_on_exit = true
