root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -C encounter-service -buildvcs=false -o tmp/main igaku/encounter-service"
bin = "encounter-service/tmp/main"
include_ext = ["go"]
exclude_dir = ["encounter-service/tmp", "encounter-service/bin"]
log = "air_encounter.log"
delay = 1000

[misc]
clean_on_exit = true
