root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -C mail-service -buildvcs=false -o tmp/main igaku/mail-service"
bin = "mail-service/tmp/main"
include_ext = ["go"]
exclude_dir = ["mail-service/tmp", "mail-service/bin"]
log = "air_user.log"
delay = 1000
stop_on_error = true

[misc]
clean_on_exit = true
