root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -C user-service -buildvcs=false -o tmp/main igaku/user-service"
bin = "user-service/tmp/main"
include_ext = ["go"]
exclude_dir = ["user-service/tmp", "user-service/bin"]
log = "air_user.log"
delay = 1000

[misc]
clean_on_exit = true
